server:
  port: 8002
  
spring:  application:    name: rabbitmq-consumer
  rabbitmq:    host: 192.168.149.131
    port: 5672
    username: admin
    password: admin
    virtual-host: /test001